# -- coding: utf-8 --
# #############################################################################
#                           YOUR INMOOV CUSTOM
# Here you can add your own commands to play and test with inmoov
# If you udpate the whole script, don't worry, those commands are safe
# ##############################################################################



talk("Bonjour ! comment ça va")


ear.addCommand("ouvre les yeux", "python", "paupiereOuvre")
ear.addCommand("ferme les yeux", "python", "paupiereFerme")
ear.addCommand("bouge les sourcils", "python", "monteSourcil")
ear.addCommand("baisse les sourcils", "python", "baisseSourcil")
ear.addCommand("regarde vers la droite", "python", "regardDroit")
ear.addCommand("regarde devant", "python", "regardDevant")
ear.addCommand("regarde vers la gauche", "python", "regardGauche")
ear.addCommand("lève la tête", "python", "hautTete")
ear.addCommand("baisse la tête", "python", "basTete")
ear.addCommand("tourner la tête à gauche", "python", "teteGauche")
ear.addCommand("tourner la tête à droite", "python", "tetedroite")
ear.addCommand("repositionne la tête", "python", "teteMilieu")
ear.addCommand("reposition la tête", "python", "teteMilieu")
ear.addCommand("incline la tête à droite", "python", "inclineDroite")
ear.addCommand("incline la tête à gauche", "python", "inclineGauche")

def inclineDroite():
	verinDroite.attach()
	verinGauche.attach()
	verinDroite.moveTo(0)
	verinGauche.moveTo(180)
	sleep(5)
	verinGauche.detach()
	verinDroite.detach()

def inclineGauche():
	verinDroite.attach()
	verinGauche.attach()
	verinDroite.moveTo(180)
	verinGauche.moveTo(0)
	sleep(5)
	verinGauche.detach()
	verinDroite.detach()

def teteMilieu():
	directionTete.attach()
	directionTete.moveTo(79)

def teteDroite():
	directionTete.attach()
	directionTete.moveTo(0)

def teteGauche():
	directionTete.attach()
	directionTete.moveTo(180)
	

def basTete():
	verinDroite.attach()
	verinGauche.attach()
	verinDroite.moveTo(0)
	verinGauche.moveTo(0)
	sleep(5)
	verinGauche.detach()
	verinDroite.detach()

def hautTete():
	verinDroite.attach()
	verinGauche.attach()
	verinDroite.moveTo(150)
	verinGauche.moveTo(140)
	sleep(5)
	verinGauche.detach()
	verinDroite.detach()
	
	
def paupiereOuvre():
	paupiereHautDroit.attach()
	paupiereBasGauche.attach()
	rotationCylindre.attach()
	paupiereBasDroit.attach()
	paupiereHautGauche.attach()
	berceau.attach()
	paupiereHautDroit.moveTo(180)
	paupiereHautGauche.moveTo(180)
	paupiereBasDroit.moveTo(180)
	paupiereBasGauche.moveTo(180)
	rotationCylindre.moveTo(180)
	berceau.moveTo(180)

def paupiereFerme():
	paupiereHautDroit.attach()
	paupiereBasGauche.attach()
	rotationCylindre.attach()
	paupiereBasDroit.attach()
	paupiereHautGauche.attach()
	paupiereHautDroit.moveTo(0)
	paupiereHautGauche.moveTo(0)
	paupiereBasDroit.moveTo(0)
	paupiereBasGauche.moveTo(0)
	rotationCylindre.moveTo(0)
	berceau.moveTo(0)
	sourcilDroit.moveTo(90)
	sourcilGauche.moveTo(90)

def monteSourcil():
	sourcilDroit.attach()
	sourcilGauche.attach()
	sourcilDroit.moveTo(180)
	sourcilGauche.moveTo(180)
	
def baisseSourcil():
	sourcilDroit.attach()
	sourcilGauche.attach()
	sourcilDroit.moveTo(0)
	sourcilGauche.moveTo(0)
	
def regardDroit():
	oeilDroit.attach()
	oeilGauche.attach()
	oeilDroit.moveTo(0)
	oeilGauche.moveTo(0)
	
def regardGauche():
	oeilDroit.attach()
	oeilGauche.attach()
	oeilDroit.moveTo(180)
	oeilGauche.moveTo(180)

def regardDevant():
	oeilDroit.attach()
	oeilGauche.attach()
	oeilDroit.moveTo(113)
	oeilGauche.moveTo(98)
	
def open():
	rotationCylindre.attach()
	berceau.attach()
	paupiereBasDroit.attach()
	paupiereBasGauche.attach()
	paupiereHautDroit.attach()
	paupiereHautGauche.attach()
	sourcilDroit.attach()
	sourcilGauche.attach()
	verinGauche.attach()
	verinDroite.attach()
	rotationCylindre.moveTo(90)
	berceau.moveTo(180)
	paupiereBasDroit.moveTo(180)
	paupiereBasGauche.moveTo(180)
	paupiereHautDroit.moveTo(35)
	paupiereHautGauche.moveTo(35)
	sourcilDroit.moveTo(35)
	sourcilGauche.moveTo(35)
	verinGauche.moveTo(110)
	verinDroite.moveTo(115)
	sleep(3)
	verinGauche.detach()
	verinDroite.detach()
	
def curieu():
	rotationCylindre.attach()
	berceau.attach()
	paupiereBasDroit.attach()
	paupiereBasGauche.attach()
	paupiereHautDroit.attach()
	paupiereHautGauche.attach()
	sourcilDroit.attach()
	sourcilGauche.attach()
	verinGauche.attach()
	verinDroite.attach()
	rotationCylindre.moveTo(30)
	berceau.moveTo(0)
	paupiereBasDroit.moveTo(180)
	paupiereBasGauche.moveTo(180)
	paupiereHautDroit.moveTo(180)
	paupiereHautGauche.moveTo(180)
	sourcilDroit.moveTo(180)
	sourcilGauche.moveTo(70)
	verinGauche.moveTo(110)
	verinDroite.moveTo(50)
	sleep(3)
	verinGauche.detach()
	verinDroite.detach()
	
def surpris():
	rotationCylindre.attach()
	berceau.attach()
	paupiereBasDroit.attach()
	paupiereBasGauche.attach()
	paupiereHautDroit.attach()
	paupiereHautGauche.attach()
	sourcilDroit.attach()
	sourcilGauche.attach()
	verinGauche.attach()
	verinDroite.attach()
	rotationCylindre.moveTo(170)
	berceau.moveTo(180)
	paupiereBasDroit.moveTo(180)
	paupiereBasGauche.moveTo(180)
	paupiereHautDroit.moveTo(180)
	paupiereHautGauche.moveTo(180)
	sourcilDroit.moveTo(35)
	sourcilGauche.moveTo(35)
	verinGauche.moveTo(110)
	verinDroite.moveTo(115)
	sleep(3)
	verinGauche.detach()
	verinDroite.detach()
	
def mechant():
	rotationCylindre.attach()
	berceau.attach()
	paupiereBasDroit.attach()
	paupiereBasGauche.attach()
	paupiereHautDroit.attach()
	paupiereHautGauche.attach()
	paupiereBasDroit.attach()
	paupiereBasGauche.attach()
	sourcilDroit.attach()
	sourcilGauche.attach()
	verinGauche.attach()
	verinDroite.attach()
	rotationCylindre.moveTo(0)
	berceau.moveTo(0)
	paupiereBasDroit.moveTo(180)
	paupiereBasGauche.moveTo(180)
	paupiereHautDroit.moveTo(35)
	paupiereHautGauche.moveTo(35)
	paupiereBasDroit.moveTo(60)
	paupiereBasGauche.moveTo(60)
	sourcilDroit.moveTo(180)
	sourcilGauche.moveTo(180)
	verinGauche.moveTo(110)
	verinDroite.moveTo(115)
	sleep(3)
	verinGauche.detach()
	verinDroite.detach()
	
def cleinOeil():
	rotationCylindre.attach()
	berceau.attach()
	paupiereBasDroit.attach()
	paupiereBasGauche.attach()
	paupiereHautDroit.attach()
	paupiereHautGauche.attach()
	sourcilDroit.attach()
	sourcilGauche.attach()
	verinGauche.attach()
	verinDroite.attach()
	rotationCylindre.moveTo(0)
	berceau.moveTo(0)
	paupiereBasDroit.moveTo(0)
	paupiereHautDroit.moveTo(0)
	paupiereHautGauche.moveTo(180)
	sourcilDroit.moveTo(90)
	sourcilGauche.moveTo(120)
	verinGauche.moveTo(110)
	verinDroite.moveTo(35)
	sleep(1)
	rotationCylindre.moveTo(90)
	berceau.moveTo(180)
	paupiereBasDroit.moveTo(180)
	paupiereBasGauche.moveTo(180)
	paupiereHautDroit.moveTo(35)
	paupiereHautGauche.moveTo(35)
	sourcilDroit.moveTo(35)
	sourcilGauche.moveTo(35)
	verinGauche.moveTo(110)
	verinDroite.moveTo(115)
	sleep(3)
	verinGauche.detach()
	verinDroite.detach()
	
verinGauche.detach()
verinDroite.detach()